name: ehrml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - duckdb
  - fastapi
  - httpx
  - matplotlib
  - pandas
  - pyyaml=6.0
  - pytest
  - shap
  - tabulate=0.9.0
  - uvicorn=0.35.0
  - xgboost
  - pip
  - pip:
    - httpx
    - xgboost